name: Deploy Qubic Madrid

on:
  push:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        default: "madrid-2025"

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 4
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || 'madrid-2025' }}

      - name: Deploy Qubic
        run: |
          echo "tototo" | sudo -S bash -c "
          echo 'Running cleanup...' && sleep 2 && \
          cd /root/qubic/qubic_docker && \
          ./cleanup.sh && sleep 2 && \
          cd /root/qubic/qubic_docker && \
          ./cleanup.sh && sleep 2 && \
          cd /root/qubic/qubic_docker && \
          ./cleanup.sh && \
          echo 'Running deploy...' && \
          cd /root/qubic/qubic_docker && \
          ./deploy.sh https://github.com/Qubic-Qulang/core/tree/${{ github.event.inputs.branch || github.ref_name }}"
